name: autofix.ci

on:
  pull_request:
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  autofix:
    runs-on: ubicloud-standard-2

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - name: Lint
        run: npm run lint -- --fix
        shell: bash

      - name: Typecheck
        run: npm run build
        shell: bash
        env:
          GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
          GH_WEBHOOK_SECRET: ${{ secrets.GH_WEBHOOK_SECRET }}

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
